apiVersion: v1
kind: Service
metadata:
  name: superhost
  labels:
    app: superhost
spec:
  type: NodePort
  ports:
  - name: server
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: superhost